name: customflutterdatetimepicker
description: custom datepicke from package flutter_datetime_picker https://pub.dev/packages/flutter_datetime_picker
version: 0.0.1
author: Ratchawit Srithongdee
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: